### ISSUE TITLE
when I run the function breast_cancer.py, I got this error. please can anyone help me to solve it urgently?

### ISSUE THREAD

**Issue by BassantTolba1234** [Qiskit/qiskit-machine-learning#454] opened 2022-08-16 10:50 UTC
### Environment

- **Qiskit Machine Learning version**:
- **Python version**: 
- **Operating system**: 

### What is happening?

![image](https://user-images.githubusercontent.com/59363587/184861712-043e1b09-79fc-4351-9a95-88dbe29df1bb.png)
when I run the function breast_cancer.py, I got this error. please can anyone help me to solve it urgently?

[<ipython-input-12-b2deb6744feb>](https://localhost:8080/#) in <dictcomp>(.0)
     40     training_input = {
     41         key: (sample_train[label_train == k, :])[:training_size]
---> 42         for k, key in enumerate(class_labels)
     43     }
     44     test_input = {

TypeError: slice indices must be integers or None or have an __index__ method

### How can we reproduce the issue?

run the function breast_cancer.py, you will get this error. please can anyone help me to solve it urgently?

[<ipython-input-12-b2deb6744feb>](https://localhost:8080/#) in <dictcomp>(.0)
     40     training_input = {
     41         key: (sample_train[label_train == k, :])[:training_size]
---> 42         for k, key in enumerate(class_labels)
     43     }
     44     test_input = {

TypeError: slice indices must be integers or None or have an __index__ method

### What should happen?

brast_canser.py should be run and generate the train and test dataset

**Comment by adekusar-drl** [comment] 2022-08-16 12:16
What you posted is not a script to reproduce the issue, unfortunately. The script `breast_cancer.py` is not intended to be run directly as you proposed. Can you please post a snippet to reproduce the issue?

These lines work perfectly well:
```python
from qiskit_machine_learning.datasets import breast_cancer

ds = breast_cancer(100, 20, 4)
print(ds)
```

**Comment by BassantTolba1234** [comment] 2022-08-16 12:20
Yes, I got it. You are right. I put the values of training size and testing
size as a ratio. Thank you very much. Please, is there a version of quantum
gan that uses breast_cancer,py as a dataset to reproduce it??

Thanks a million

Now, I will try to run qgan.. is it run

**Comment by adekusar-drl** [comment] 2022-08-16 12:24
No, I'm not aware of a QGAN example on the breast cancer dataset. 
I'm closing this issue as resolved. Feel free re-open if the issue persists.

**Closed by adekusar-drl** 2022-08-16 12:24 UTC
